version: '3.3'

services:
  nginx:
    image: lherman/arm-nginx
    container_name: nginx
    restart: always
    ports:
      - 8443:8443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ${KEY_DIR}:/mnt
    depends_on:
      - aria
      - ytdl
      - plex
      - docker-ui
  aria:
    image: lherman/aria2
    container_name: aria
    restart: always
    expose:
      - 6800
      - 8080
    volumes:
      - ./aria2:/data/.aria2
      - ./data:/data
      - ${KEY_DIR}:/mnt
  ytdl:
    image: lherman/ytdl-webui
    container_name: ytdl
    restart: always
    expose:
      - 1323
    volumes:
      - ./data:/go/src/app/data
  plex:
    image: jaymoulin/rpi-plex
    container_name: plex
    restart: always
    expose:
      - 32400
    volumes:
      - ./plex:/media
      - ./data:/root/Library
  docker-ui:
    image: portainer/portainer
    container_name: docker-ui
    restart: always
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
